name = "NetworksCourse"
uuid = "58ebc9ab-8014-47c1-97cd-ebccb17d045e"
authors = ["Fabian Greimel <fabgrei@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
